#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  creationTimestamp: null
#  name: php-apache
#spec:
#  maxReplicas: 10
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: php-apache
#  targetCPUUtilizationPercentage: 50


#  HorizontalPodAutoscaler 将会尝试确保每个 Pod 的 CPU 利用率在 50% 以内， 每秒能够服务 1000 个数据包请求， 并确保所有在 Ingress 后的 Pod 每秒能够服务的请求总数达到 10000 个。

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: AverageValue
#          averageValue : 1
#        target:
#          type: AverageUtilization
#          averageUtilization: 50
    - type: Pods
      pods:
        metric:
          name: packets-per-second   # 监控系统能够提供网络流量数据
        target:
          type: AverageValue
          averageValue: 1k
    - type: Object
      object:
        metric:
          name: requests-per-second   # 监控系统能够提供网络流量数据
        describedObject:
          apiVersion: networking.k8s.io/v1beta1
          kind: Ingress
          name: main-route
        target:
          kind: Value
          value: 10k
